### ISSUE TITLE
Not working with xss-lock

### ISSUE THREAD

**Issue by samhh** [muennich/physlock#102]
I've seen comments here and elsewhere about pairing physlock with xss-lock, but it doesn't seem to be working for me on Arch with the latest of each. `$ xss-lock physlock` / `$ xss-lock -- physlock` / `$ xss-lock -- physlock -d` / `$ xss-lock "/usr/bin/physlock"` - with any of these physlock doesn't pop up after waking up from suspend (triggered with `$ systemctl suspend`), but there _is_ a physlock process open each time which there wasn't previously. Running just `$ physlock` on its own works as expected. Any ideas? Cheers.

**Comment by Barbaross93** [comment]
Try `xss-lock -l -- physlock`

The `-l` flag facilitates transferring the lock when the system is suspending/hibernating. It works for me, hopefully it does for you!

**Comment by samhh** [comment]
Wow, the one combination I hadn't tried, closest I got before was without the `--`. Thanks @loki7990!!
