### ISSUE TITLE
Feature request: Don't ask which user will unlock.

### ISSUE THREAD

**Issue by marcoamorales** [muennich/physlock#15]
I searched for this option but I couldn't find it. Could it be possible to add a feature to default to a user and not ask which user is going to unlock the screen?

My biggest concern with this is that in my personal case, I'm very used to just typing my password and unlocking the computer, and it's dangerous to accidentally type my password in the user field.

**Comment by muennich** [comment]
Please have a look at pull request #4, its patch set might solve your issue. As I've already said there, I do not like the idea of disabling the ability to always unlock as root.
