### ISSUE TITLE
starting and killing physlock via ssh leaves screen locked forever

### ISSUE THREAD

**Issue by ceremcem** [muennich/physlock#16]
Hi, 

Calling `physlock` and immediately pressing `Ctrl+C` and `Ctrl+Z` killed physlock but leaves screen locked. `killall -9 physlock` does not help.

**Comment by muennich** [comment]
How do you start physlock? I am unable to reproduce this; physlock disables some signals including SIGINT (Ctrl-C) before doing anything else.

**Comment by ceremcem** [comment]
Sorry about missing information. I'm logging in via SSH and then I'm starting physlock as: 
  
    $ physlock

Then physlock locks screen and I can still have access to the command line. Then I send `Ctrl+C, Ctrl+Z`; then the screen which physlock locked a moment ago is left locked forever. Only way is to reboot the box.

**Comment by muennich** [comment]
physlock should ignore the `Ctrl-c`. Does this also happen when you're only using `Ctrl-z`?

**Comment by ceremcem** [comment]
This issue happens only when `Ctrl-z` is used only. `Ctrl-c` is simply ignored.

**Comment by muennich** [comment]
So, you are simply stopping physlock with `Ctrl-z`. Are you then using `fg` or `bg` to resume it? If not, then physlock does not do anything at all--and so nothing wrong--because it remains in the stopped state.

**Comment by ceremcem** [comment]
I tried `sudo killall physlock` before but it didn't help. Now as you suggested I tried `fg` after stopping by `Ctrl-z`, it responded as expected. I achieved the expected behaviour by using the following commands in order: 

    $ physlock
    Ctrl-z
    $ sudo killall physlock
    $ fg

Thank you for your help.
