### ISSUE TITLE
Physlock systemd service failing

### ISSUE THREAD

**Issue by fowlslegs** [muennich/physlock#17]
I am using the systemd service described in #10 (the second one posted) and am getting this error. No matter what password I enter, the screen will unlock.

    Apr 26 20:42:26 dom0 physlock[25832]: physlock: error: could not hash password for user root
    Apr 26 20:42:26 dom0 systemd[1]: physlock.service: main process exited, code=exited, status=1/FAILURE
    Apr 26 20:42:26 dom0 systemd[1]: Unit physlock.service entered failed state.

**Comment by fowlslegs** [comment]
Solved it. Funny solution. Qubes has no root password by default. There is usually no need for one so you aren't asked to create it during install.

**Comment by muennich** [comment]
I will add a dry authentication run for the root user at startup, so that physlock does fail before switching the screen.
