### ISSUE TITLE
mdoc

### ISSUE THREAD

**Issue by Pyrohh** [muennich/physlock#18]
Would you be averse to me converting the man page to mdoc? The primary difference is it uses semantic macros instead of presentation macros; more information here http://mdocml.bsd.lv/.

groff has had a comprehensive mdoc implementation for quite some time now ([1.17 had a complete mdoc rewrite apparently](http://git.savannah.gnu.org/cgit/groff.git/tree/NEWS), which was released [a long time ago](https://ftp.gnu.org/gnu/groff/old/)).

Of course it's fine if you'd rather not, considering it's a different language and the existing man page works well enough, but I think roff leaves a lot to be desired (hence the issue).

**Comment by muennich** [comment]
Roff works for me, so I'm not really interested in switching. Thanks for offering your help anyhow.
