### ISSUE TITLE
"could not deallocate console # 2: Device or resource busy"

### ISSUE THREAD

**Issue by mindstormer12** [muennich/physlock#22]
I installed physlock through the AUR (Arch Linux) then ran "physlock -d & sudo systemctl hibernate" after adding the following service and enabling it: 

/etc/systemd/system/screensaver.service

[Unit]
Description=Lock session
Before=sleep.target

[Service]
Type=simple
ExecStart=/usr/bin/physlock -d -u myname

[Install]
WantedBy=sleep.target

I then get the error: "could not deallocate console # 2: Device or resource busy" when I log in to my locked session.

Am I setting up physlock + hibernation properly or is this a bug?

**Comment by muennich** [comment]
You need to either run the command line `physlock -d & sudo systemctl hibernate` or create a service file as above and then only run `sudo systemctl hibernate`. Also, the `Type` of the service file should be set to `forking`.

**Comment by mindstormer12** [comment]
All I did was change "Type=simple" to "Type=forking" and running "systemctl hibernate" works (I'm very new to Linux, not sure why sudo is necessary when just "systemctl hibernate" seems to be working. (If you could answer that, that would be great). Closing this issue, and thanks!
