### ISSUE TITLE
Offer an option to always allow the root user to unlock

### ISSUE THREAD

**Issue by HalosGhost** [muennich/physlock#23]
While I appreciate the fancy new mechanism for determining the user which is allowed to unlock, and allowing fallback to root after three failed attempts, I actually appreciated the ability to unlock as the root user.

Is there a chance you would be willing to add an option to always allow the root user to unlock (the old behavior)?

**Comment by muennich** [comment]
What exactly do you mean with always allowing root to unlock? The prompt for the user name? This will not come back. The root user can always unlock, he only has to hit enter 3 times and wait a couple of seconds, no big deal if you ask me.

**Comment by HalosGhost** [comment]
Indeed, I was hoping for the prompt to come back. Sounds fair though; I suppose you should mark as `WONTFIX` then :)
