### ISSUE TITLE
Hibernating more than once does not work properly in X only (reproducible with information)

### ISSUE THREAD

**Issue by mindstormer12** [muennich/physlock#24]
Execution of multiple hibernations via <`systemctl hibernate`> is working as expected in virtual consoles.

Problem: First execution of hibernation in X works as expected. Any other multiple executions of hibernate of the same *user session*, not *X session* will result in the screen being locked but not hibernating. Entering the password will bring me back to my session (again, never hibernating). Running `<systemctl hibernate>` again will result in "Failed to execute operation: There's already a shutdown or sleep operation in progress" and I can no longer us `<systemctl hibernate/suspend/poweroff>` as a result (so I manually shutdown the computer).

My screenlocker.service, enabled:

>[Unit]
>Description=Lock X session
>Before=hibernate.target

>[Service]
>Type=forking
>ExecStart=/usr/bin/physlock -d -u mindstormer

>[Install]
>WantedBy=hibernate.target

Without using physlock -d at all, normally hibernating multiple times in X has no issues, working as expected.

P.S. another potential bug (minor): On occasion (more than I would like), when I hibernate in X, returning back to the session after entering my password will bring me to a black screen with a cursor blinking. I have to manually ALT + F1 for it to show my session.

**Comment by muennich** [comment]
Can you post the output of `systemctl --failed` and `systemctl status screenlocker.service`?

**Comment by mindstormer12** [comment]
0 loaded units listed (did not pass --all)

Loaded: loaded (/etc/systemd/system/screenlocker.service; enabled; vendor preset: disabled)
Active: inactive (dead)

**Comment by muennich** [comment]
Are these outputs generated after returning from a failed hibernation?

**Comment by AladW** [comment]
Does it work with this service:
```
[Unit]
Description=Lock all sessions
Before=sleep.target

[Service]
Type=forking
ExecStart=/usr/bin/physlock-user
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
```

Notice the ExecStartPost

**Comment by mindstormer12** [comment]
Awesome, that solved it. Could you tell me why adding ExecStartPost=/usr/bin/sleep 1 worked? Also, will this one service work for both hibernate and suspend or just hibernate? I can't use suspend on my VM at all for some reason so I can't test it out.

Thanks.
