### ISSUE TITLE
Unable to determine keyboard layout on the lock screen

### ISSUE THREAD

**Issue by p-himik** [muennich/physlock#27]
It's still possible to switch keyboard layout when physlock is active.
Currently there is no way to determine the layout which may lead to authentication failures.

**Comment by muennich** [comment]
Is there even a way to detect the active keyboard layout on a Linux console?

**Comment by p-himik** [comment]
I have no idea - I very rarely touch C. But even if it's not possible, there should be some way to get over it, though I guess it will depend on X or Dbus and should be user configurable.

And just an hour ago I had a related situation. I tried to wake my laptop up from suspend. It seems that before the suspension, the layout for physlock has been changed by kbdd (my keybindings for suspension at this moment include the keybindings for layout switching which sometimes leads to layout switching for current window right before suspension) and either kbdd has never woke up or something similar happened as I wasn't able to switch layout anymore. Basically, I was stuck with an impassable login prompt.

Clearly I wouldn't been able to login in this situation even if I new what the current layout is. Do you have any suggestion on how it may be dealt with? I definitely change some of my keybindings, but maybe there is something that can be done in physlock. E.g. a user passes the needed keyboard layout as physlock's argument and physlock makes sure that only this layout is available and active. As far as I know layout switching is possible from console.

**Comment by muennich** [comment]
X or DBus dependencies won't happen.

X and console keyboard layouts are two different things. kbdd changes the keyboard layout for X. How does this affect the layout on your consoles? And how are you able to change the layout while physlock is running? Maybe you're better off with a screenlocker for X.

**Comment by p-himik** [comment]
Turned out I have layout switching configured in consoles as well, it must have been configured during the system setup. Not sure why after suspend it once got stuck in one layout - probably a bug not related to physlock.

Regarding a way to detect active keyboard layout on a Linux console - apparently it can be done by matching current keyboard translation table with tables generated by particular layouts. Clearly it's not to be implemented in physlock, and I couldn't find any existing facility for this, but it still is possible.

What do you think about my suggestion of locking a layout predefined by user for one instance of physlock? Like calling "loadkeys us_only_table; physlock; loadkeys default_table" only from inside physlock.

**Comment by muennich** [comment]
Why should this be done by physlock itself? There's no advantage over the compound command line using `loadkeys`. And both cases do not prevent a layout change from another process running in the background.

**Comment by p-himik** [comment]
The only advantage I can think of is the ease of use. But since at this point it looks like I'm the only one with such problem, I'll just solve it locally with a script and close this issue.
Thank you for your time.
