### ISSUE TITLE
'physlock -d' not working in the Linux console

### ISSUE THREAD

**Issue by tty-tourist** [muennich/physlock#30]
I'm running Debian 8.2 on a machine without X installed, only the Linux console and fbterm.

When I run:
`physlock -d`

I get this message:
`physlock: /dev/console: VT_DISALLOCATE: Device or resource busy`

Curiously the tty with a number one higher than the current will show the lock screen when I switch to that tty. For example, if I run `physlock -d` in tty1 I will get the error above, and when I switch to tty2, that tty will be locked.

This applies both when running `physlock -d` from fbterm or vanilla Linux console.

'physlock -d' has worked for me with earlier version. Unfortunately I can't say exactly which versions as I have wiped my disks since then.

**Comment by muennich** [comment]
Commit a634875 fixes this issue for me.

**Comment by tbeitter** [comment]
I still got that issue with v11

When physlock got called by systemd I see it on my screen before the password prompt. When manually called from a terminal I see it after unlocking.

**Comment by pigmonkey** [comment]
I have also begun seeing this VT_DISALLOCATE message. For me it only began with v11. I see the  message whether launching from within X or outside of it. It occurs both when running `physlock` without any flags, as well as `physlock -d`.

The lock screen still works fine. I just end up with the message either before the password prompt or within the terminal depending on how I launched physlock, as @tbeitter described.

**Comment by bddenhartog** [comment]
Installed `physlock` from the AUR and experienced the `VT_DISALLOCATE: device or resource busy` message.

Noticed that it was v11; removed it and installed `physlock-git` (version `git-20170918`). Commit 241af6c resolves this issue - any idea when you'll be tagging a new release?

**Comment by muennich** [comment]
I do not consider the error message a huge problem, as only `VT_DISALLOCATE` fails. This happens during cleanup when physlock is done and the resources get freed nonetheless when physlock exits.

**Comment by bddenhartog** [comment]
> I do not consider the error message a huge problem, as only VT_DISALLOCATE fails. This happens during cleanup when physlock is done and the resources get freed nonetheless when physlock exits.

Right -- agreed that it's not a huge problem, just an unsightly one to new users who might not understand it. I left my comment simply so users who, like me, installed the non-development version from the AUR would have a solution (well, and to also ask you when we could expect a new release, that might include this).
