### ISSUE TITLE
Implicit user identification (using utmp) fails

### ISSUE THREAD

**Issue by elboulangero** [muennich/physlock#31]
Hi !

on my system, the utmp mechanism to identify the active physical user (introduced by f02467f) fails.

    $ sudo physlock
    physlock: /var/run/utmp: No entry for tty2 found

Here is the output of the `w` command for me:
```
$ w
 10:39:24 up 2 min,  2 users,  load average: 1.16, 0.74, 0.30
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
art      pts/0    :0.0             10:38    2.00s  0.03s  0.03s /bin/bash
art      pts/1    :0.0             10:39    4.00s  0.03s  0.00s w
```

As you can see, I have 2 terminals opened. They're all identified by `pts/x`. The problem is that physlock tries to match the string `tty2` with one of the `pts/x` lines.

To be mo accurate, I'm talking about the line `if (strcmp(r.ut_line, tty) == 0)`, in `get_user()` function in file `auth.c`. The successive values for `r.ut_line` are `pts/0`, `pts/1` and so on if I have more terminals opened.

Here is a dump of the entries of `struct utmp`, that I made simply by adding some `printf()` calls to the function `get_user()`.

```
$ sudo ./physlock
Reading entry...
r.ut_type: 2
r.ut_pid : 0
r.ut_line: ~
r.ut_id  : ~~
r.ut_user: reboot
r.ut_host: 4.2.0-1-amd64
Reading entry...
r.ut_type: 6
r.ut_pid : 803
r.ut_line: tty1
r.ut_id  : tty1LOGIN
r.ut_user: LOGIN
r.ut_host:
Reading entry...
r.ut_type: 1
r.ut_pid : 53
r.ut_line: ~
r.ut_id  : ~~
r.ut_user: runlevel
r.ut_host: 4.2.0-1-amd64
Reading entry...
r.ut_type: 7
r.ut_pid : 1468
r.ut_line: pts/0
r.ut_id  : /0
r.ut_user: art
r.ut_host: :0.0
Reading entry...
r.ut_type: 7
r.ut_pid : 1468
r.ut_line: pts/1
r.ut_id  : /1
r.ut_user: art
r.ut_host: :0.0
Reading entry...
physlock: /var/run/utmp: No entry for tty2 found
```
One last command...

    $ uname -a
    Linux gazelle 4.2.0-1-amd64 #1 SMP Debian 4.2.6-2 (2015-12-04) x86_64 GNU/Linux

Any idea ?

**Comment by muennich** [comment]
physlock only looks for the utmp entry belonging to the foreground tty, because it describes the active physical session. The program you're using to log into your computer does not write an utmp entry. Please have a look at issue #25, it's a possible duplicate of this issue.

**Comment by elboulangero** [comment]
Hey !

Thanks for the explanations. Indeed this is a duplicate of #25, my bad.

I use `slim` as a login manager. I managed to get it to write the proper utmp entry with theses lines:

    sessionstart_cmd    /usr/bin/sessreg -a -l tty$(fgconsole) %user
    sessionstop_cmd     /usr/bin/sessreg -d -l tty$(fgconsole) %user

Here are my other attempts that didn't succeed: 

- `sessionstart_cmd /usr/bin/sessreg -a -l $DISPLAY %user` (mentioned in <https://wiki.archlinux.org/index.php/SLiM#Login_information_with_SLiM> adds an entry, but the line name is the same as `echo $DISPLAY`, that's `:0.0`
- `sessionstart_cmd /usr/bin/sessreg -a %user` doesn't add any entry. Maybe it's due to the error mentioned by @bitcrush in #25, but I can't see the error message, if any, when the command is run by slim. Though if I run that manually in my console (after being logged in, and as root), it adds an entry, but the line name is `pts/0`, which is the name of the current virtual terminal, of course...

Anyway, just wanted to know, what should I understand from this ? That physlock is not exactly made to run from a X session ? Or that my session manager (slim) doesn't do the things properly ? What's your use case ? Just trying to get a deeper understanding here, since I don't know much on this topic, and you seem to know a lot more than me :)

**Comment by muennich** [comment]
physlock is useful if you often have active logins on multiple ttys and want to lock them all at once. If you only have one X session all the time, then a simple X screen locker like [slock](http://tools.suckless.org/slock/) might serve you better.

Nevertheless, two mechanisms have been used in the past by console `login(1)` and X display managers to indicate the user logged in on a tty: writing an appropriate entry into the utmp file and/or setting the owner of the corresponding `/dev/ttyX` file (^1). However, a growing number of login programs do not do that anymore. I suspect there is some dbus API provided by systemd's logind, but I do not have the time to look into this.

If someone knows a universal way to detect the user of the active tty then please tell me. In the meantime physlock has to rely on utmp, so we have to make sure that our login programs write appropriate entries into it.

Footnote 1: Some X display managers use the name of the display for the `ut_line` member of their entries, others use the name of the tty as `login(1)` does. The former only complicates things, as the mapping of displays to ttys is not obvious and as such is not supported by physlock.

**Comment by elboulangero** [comment]
Great explanations, really appreciated. Thanks for taking some time on this topic :smile:

**Comment by CMCDragonkai** [comment]
I'm having this problem now when using XMonad on NixOS: I get `physlock: /var/run/utmp: No entry for tty7 found`. Running `sudo w` shows 0 users.

**Comment by kamilchm** [comment]
@CMCDragonkai if you use slim, this works https://github.com/kamilchm/nixos-config/blob/master/configuration.nix#L145-L148

**Comment by CMCDragonkai** [comment]
Is there something similar for sddm?

**Comment by Tmplt** [comment]
For any future NixOS users who stumble in here: allowing non-root to run physlock can be done with

```nix
security.wrappers.physlock {
  source = "${pkgs.physlock}/bin/physlock";
  user = "root";
}
```

Do note the security implications, though. physlock is now root for all intents and purposes.

**Comment by pavlix** [comment]
@muennich What I don't like about slock and similar tools is that they actually require to be run as the user and therefore it is not so easy to call them from the system e.g. on suspend. Any sugestions?
