### ISSUE TITLE
Unsafe copy of strings from utmp struct

### ISSUE THREAD

**Issue by elboulangero** [muennich/physlock#32]
Hi !

While reading the utmp manual, I stumbled on that line:
> String fields are terminated by a null byte ('\0') if they are shorter than the size of the field.

Notice the `if they are shorter` ? Apparently the guys liked to set little traps around for people writing code ;)

Anyway, so I see in physlock that the field `r.ut_user` from `struct utmp` is copied recklessly, expecting a trailing `\0`. It's probably a bit dangerous.

**Comment by muennich** [comment]
Thanks for reporting this.
