### ISSUE TITLE
feature request: Don't print typed charracters to screen

### ISSUE THREAD

**Issue by magnetophon** [muennich/physlock#33]
When you forget to hit ``<Return>``, or you don't hit it properly, everyone get's to see your password.
Sure, it's user error, but (I hope) it'd be easy to fix.

Is there a reason for printing what is typed at all?

**Comment by muennich** [comment]
Are you using a stable release? The current master seems to do what you're asking for.

**Comment by magnetophon** [comment]
I'm using:
```
physlock -v
physlock git-20150126 - lock all consoles
```
Which is the version in my distro: NixOS.

**Comment by muennich** [comment]
So, your problem does not apply to the current master; there's nothing for me to do. All that's needed is an update of the NixOS package.

**Comment by magnetophon** [comment]
OK, thanks!
