### ISSUE TITLE
Allow disable of Ctrl+Alt+Del while physlock is active

### ISSUE THREAD

**Issue by AnAverageHuman** [muennich/physlock#35]
I am used to having to press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd> to unlock my Windows workstation, so I often accidentally do that key sequence when coming back to my computer, resulting in it rebooting. Would it be possible to add an argument that temporarily disables  <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Del</kbd> while physlock is active?

**Comment by ivan** [comment]
I had the same problem and disabled this with

```
systemctl mask ctrl-alt-del.target
systemctl daemon-reload
```

though systemd will still reboot the system immediately if you press Ctrl-Alt-Delete 7 times within 2 seconds

**Comment by AnAverageHuman** [comment]
Nice solution - fixes the problem but doesn't completely disable the key sequence.
