### ISSUE TITLE
Errors upon unlocking

### ISSUE THREAD

**Issue by CMCDragonkai** [muennich/physlock#36]
I'm getting these 2 errors after unlocking. What could they mean?

```
physlock: error: could not hash password for user root
physlock: error: could not deallocate console # 2: Device or resource busy
```

**Comment by muennich** [comment]
What version of physlock are you running? The first error is handled completely different in the current stable release (0.5). Older versions of physlock died when they were unable to get the password for the root user; dying meant no locking of the screen and therefore no password prompt. The second only indicates that physlock has trouble freeing it's resources when it's done.

**Comment by CMCDragonkai** [comment]
The version is:

```
> physlock -v
physlock git-20150126 - lock all consoles
```

The second error changes console number each time.

I'm running on NixOS.

**Comment by muennich** [comment]
You're using a pretty old version of physlock and as such are running into issue #17. Please upgrade to the current stable version.
