### ISSUE TITLE
DPMS not applied when physlock is running

### ISSUE THREAD

**Issue by githububub** [muennich/physlock#37]
No system suspend or hibernation. Running phylock both manually through terminal and via xautolock physlock in .xinitrc. xset dpms in .xinitrc.  DPMS does not apply when physlock is running = LED screen is on for hours when it can save energy in monitor standby/suspension.

**Comment by muennich** [comment]
physlock uses a virtual terminal (/dev/ttyX) for the lock screen. X's DPMS settings have no effect there. Duplicate of issue #9.
