### ISSUE TITLE
command line option for user whose password to ask

### ISSUE THREAD

**Issue by sergeev917** [muennich/physlock#39]
The current setup with mandatory utmp lookup works great for pure vt users, but for x11 sessions there could be complications. I don't have xorg server running by default and I use `startx` to start X server. The problem is that if I use physlock when the allocated for xorg server vt is active I get 

`physlock: /var/run/utmp: No entry for tty<redacted> found`.

It would be great to have means of providing/overriding a user instead of tty owner lookup, since the only way to use `physlock` for me is to manage vt switches and run login (which is an overkill, whether it's automated or not). Another option is to tackle utmp, but additional flexibility for `physlock` could help better.

**Comment by muennich** [comment]
Duplicate of issue #25.

**Comment by sergeev917** [comment]
`sessreg` requires root privileges which is not always an option with `startx`. There is no root-enabled desktop manager running (no manager at all, to be precise) in my case.
My point was that I can do something like this:

`who | grep $(cat /sys/class/tty/tty0/active) | awk '{ print $1 }'`

It gives me username for currently active vt. I can do `vt_get_current` + `get_user` by myself (if it would be missing). But I can't workaround enforced session record lookup, which is little upsetting from my standpoint.

Anyway, I can easily user-epatch this in gentoo, but I thought it would be great to have more flexibility in the upstream itself.

**Comment by muennich** [comment]
But doesn't your command line still need an utmp entry for the tty X is running on?

Over the years, I've tried multiple ways to retrieve the active user in physlock. None worked a 100%. In my opinion, requiring an utmp entry for the foreground tty is still the best. Using something like `-u NAME' only shifted the problem on to the caller.

**Comment by sergeev917** [comment]
Yup, it does. I was trying to say that even if the only available interface was `-u username` (with no possible utmp lookup) I could recreate utmp lookup functionality quite easily from the caller side. It's like the username option is more basic but allows users to do whatever they might possibly want, while utmp lookup is more advanced but more restricting in the same time.

I'm not saying that utmp lookup functionality is not needed (it's certainly useful), just that the username option would be great to have for some corner cases.

**Comment by sergeev917** [comment]
In addition, utmp recording simply isn't possible with `startx`, since in this case only `X` binary runs with root uid, while `xinit`, `startx` scripts are running under regular user privilegies. Meaning that to record a session either the user should be in `utmp` group which lead to security problems or `sessreg` should be allowed by `sudo` for the user (still undesirable).

You asked earlier how is it possible to get username/uid without utmp session lookup. For me the following works:

`lsof "/dev/$(cat /sys/class/tty/tty0/active)" | sed -n '2,$s/^X\s+\([0-9]\+\).*$/\1/p' | while read pid; do cat /proc/$pid/loginuid; echo; done`

That is get the current tty device, find which processes are using this tty (looking for X server process), then check loginuid for this process which would be set by pam (pam_loginuid.so) to the user uid. The procedure could be used as a fallback when no utmp session is found (since it won't work for regular vt users, obviously).
