### ISSUE TITLE
Add option to hide user's name at prompt

### ISSUE THREAD

**Issue by craftyguy** [muennich/physlock#41]
I would like to be able to hide the user's name at the password prompt, is it possible to add this option? The reason for this is that by exposing the user's name, someone would just have to guess a password (as opposed to both user + password), and I don't want everyone that walks by my locked system to know who it belongs to :)

**Comment by muennich** [comment]
If physlock would only ask for the active user's password, the user name would not be given at the password prompt. But physlock asks for root's password every 3 failed authentication tries, so that I consider displaying the user's name necessary.

**Comment by craftyguy** [comment]
Ugh. So modify it to display "root password" after three failed attempts?

**Comment by mk-pmb** [comment]
Dunno if this was available when you asked, but it is now: You could create a user with a useless name whose only purpose is to unlock, then specify that with `-u`.

**Comment by mk-pmb** [comment]
I tried to achieve the same effect with sudo, but even when I run `sudo -iu unlock physlock` it only accepts my main user's password.
