### ISSUE TITLE
Possibility to unlock as different user

### ISSUE THREAD

**Issue by ghallberg** [muennich/physlock#43]
This might be out of scope but a suggestion at least.
I would like to be able to lock as one user, and then unlock as another user, possibly by switching tty. Is this a doable feature or will I just have to unlock as original user and then switch over?

**Comment by muennich** [comment]
The scope of physlock is to lock all ttys with the credentials of a single user. It's not suited for machines with active sessions of different users at the same time.

**Comment by ghallberg** [comment]
Ok, thanks for clarification :)

**Comment by mk-pmb** [comment]
Would it be possible to configure a list of eligible users and accept their logins to unlock, independent of who locked?
