### ISSUE TITLE
missing data in /var/run/utmp, lacking -u option to overwrite user

### ISSUE THREAD

**Issue by mika** [muennich/physlock#44]
In a live system environment we don't necessarily have according information in utmp (we're using a minimal getty based on fgetty), causing physlock to fail with:

````
physlock: /var/run/utmp: No entry for tty1 found
````

Now with the recent removal of the `-u` option it's not possible to work around this by explicitly listing the user that should be used for the locking process. This used to work fine until v0.4.5, now with 0.5 + latest git version it's failing as stated above. Any chance we might get this reworked?

Thanks for physlock!

regards,
Mika - with his hat as the Debian package maintainer of physlock

**Comment by muennich** [comment]
How is physlock called? By a user on the command line or in a system script? What about either falling back to the real user calling physlock or the user owning the device file of the foreground console?

**Comment by mika** [comment]
It's invoked manually + interactive in the command line in above example.
Falling back to the real user calling physlock and/or the user owning the device file of the foreground console sounds good to me!

**Comment by muennich** [comment]
Using the calling user breaks the core purpose of physlock: locking the computer for the user physically controlling it (i.e. the owner of the foreground console). With this change, running physlock in a remote login session controlled by a different user would lock out the user sitting in front of it.

**Comment by mika** [comment]
Hm not sure I understand it right, if I'm invoking physlock as user "mika", then I'd like to lock my computer so only user "mika" (or user root as fallback) can unlock it, no matter where I'm sitting remotely or physically at the system, nor?

(JFTR: we're invoking physlock in a live system where the invoking user has full and unrestricted sudo access anyway, so we could call it in whatever way, though current stable version as well as latest git have no way to control that in any way for us.)

**Comment by muennich** [comment]
I wrote physlock as a locking tool for a computer lab: Any user can go sit in front of a computer and log in on its console, while other users are still able to log into it remotely. The user sitting in front of the computer should be able to simply lock the physical access to the computer while going away for a short amount of time. But a remotely logged in user should not be able to lock the computer with his credentials and thus locking out the user sitting in front of it.

**Comment by mika** [comment]
Hm ok, so looks like we've conflicting use cases. :)
Any idea how we could manage to solve this?

**Comment by muennich** [comment]
Should the user be logged in on any of the `/dev/tty`s?

**Comment by mika** [comment]
Not 100% sure about that, tbh. :-/ Possibly with netboot and boot automation: no.

**Comment by muennich** [comment]
Can you please elaborate on your use case? Is physlock run even when no user is logged in?

**Comment by mika** [comment]
> Can you please elaborate on your use case?

A very specific example that comes to my mind (people are very creative with flexible live systems ;)): boot the live system (remotely), prepare everything as needed (also automated) but ensure that no one can login until the system has been properly set up (which includes setting the password for the according user as last step).
Another and more common (maybe: *the* most common) use case is to just lock the live system on-demand, since it has many auto login ttys enabled and people could mess with it. Then for sure a user is logged in in some way, though:

> Is physlock run even when no user is logged in?

In terms of data present in /var/run/utmp and that could be used for deciding on that : yes.
But users are logged in in *some* way. I'm just not sure which ways exist to reliably detect that. :-/

**Comment by muennich** [comment]
For the manual locking it might suffice that physlock falls back to the calling user if it's called from a tty (i.e. its controlling terminal is `/dev/tty?`). Not sure about your first use case though.

**Comment by mika** [comment]
If that would be available I guess that would already make 99% of our users happy. :)

**Comment by muennich** [comment]
Just for clarification: A user is logged in on a console. This console is the active one. The login is not registered in the utmp file. In this scenario the proposed change would help. However, it would be rather fragile, because running physlock in a screen or tmux session on that console would not work.

It may be better to fall back to the owner of the corresponding `/dev/tty?` device. Can you check if the auto-login procedure at least sets the logged in user as the owner of the device?

**Comment by mika** [comment]
Sorry for the delay. Just checked: yes, the owner of the corresponding /dev/tty device is set accordingly, so that fall back looks good AFAICT. Thanks!

**Comment by muennich** [comment]
Just pushed the needed changes. Enjoy!

**Comment by mika** [comment]
Oh wow, that was fast, thanks :) Sadly it doesn't seem to work for me:

````
root@grml ~ # ./physlock
physlock: Unable to detect user of tty1
root@grml ~ # ls -lah $TTY
crw------- 1 root root 4,  1 Jan  4 08:21 /dev/tty1
````

Any ideas?

Also if I'm invoking it as normal user it's complaining with "Must be root!" even though the setuid bit is set (perms are 4755), hm? :)

**Comment by muennich** [comment]
The first problem is clearly my mistake: the code did only fall back to the owner in case that the utmp file could not be opened. This should be fixed now.
Second problem: Could you check if this also happens with an older version of physlock (say 98cc054 or 7387278)?

**Comment by mika** [comment]
First problem is indeed fixed with 5202d62a01, thanks!

Second problem is already present with 98cc054, yes.

**Comment by muennich** [comment]
The setuid mechanism works for me in all versions. Could it be that your installation forbids the setuid mechanism? Maybe the filesystem with physlock on it is mounted with `nosuid` option?

**Comment by jpouellet** [comment]
So for me, this does not work.

```
$ ./physlock -v
physlock 0.5 - lock all consoles
$ ./physlock-master -v
physlock git-20170104 - lock all consoles
```

With v0.5 I get:
```
$ sudo ./physlock
physlock: /var/run/utmp: No entry for tty1 found
```

With master, my tty switches and then I get dropped to an infinite looping of
```
root:
login failed
root:
login failed
root:
login failed
```
or something like that (it's scrolling too fast to read), and after a few moments my fans start running full speed.

My system has no root login, my /dev/tty* stays owned by root:root by default, and trying to change ownership of /dev/tty{0,1} to user:user or any invocation of `sessreg -a ... $(whoami)` seems to have no affect. The auto-detection seems fragile. I miss `-u`!

**Comment by jpouellet** [comment]
FWIW, I am trying this on [Qubes OS](https://www.qubes-os.org/) w/ LightDM 1.10.6 and Xfce 4.12.1.

**Comment by jpouellet** [comment]
Okay, it appears I have two separate problems:

1. User detection wasn't working because my login manager doesn't make utmp entries, and `:0`, `:0.0`, `$DISPLAY` != `tty1`, so it seems I need to hard-code `sudo sessreg -a -l tty1 user` somewhere in my X session init path, and ensure a corresponding `sessreg -d` somehow as well. Is it expected that the tty need be hard-coded??

2. The login prompt looping is a PAM issue. I can confirm that before b76fd5fab8f2cffcafd7ec51cef5bbb0d79c9da7 it worked fine (if the expected utmp entry existed). I kind-of expected this as soon as I saw PAM in the commit logs. Sigh...

**Comment by cyrinux** [comment]
@jpouellet for the moment where do you have put sudo sessreg -a -l tty1 user?
 /etc/X11/xinit/xinitrc.d/ is a good place?

**Comment by dylangerdaly** [comment]
I'm also getting this issue with Qubes 4.0, issue sounds like it's related to PAM? Any fixes?

Want to get rid of xscreensaver...

**Comment by dylangerdaly** [comment]
Thank you, rebuilding with `SESSION=systemd` and setting up the PAM module fixed it for me.

**Comment by HalosGhost** [comment]
This just started cropping up for me. I only noticed it shortly after running a system update (on archlinux) which included the following packages:

```
fuse2 
libutil-linux 
libsystemd 
libldap 
geocode-glib 
geoclue2 
libmagick 
imagemagick 
pambase 
util-linux 
systemd 
libinput 
libqxp 
libxmlb 
libxslt 
man-db 
openldap 
pacman 
pango 
powertop 
suitesparse 
systemd-sysvcompat 
```

I would not really expect any of these to break `physlock`, but what I find stranger is that I do actually have the info showing up in `/var/run/utmp` that I expect.

Namely, `utmpdump /var/run/utmp` shows the following:
```
Utmp dump of /var/run/utmp
[2] [00000] [~~  ] [reboot  ] [~           ] [4.20.0-arch1-1-ARCH ] [0.0.0.0        ] [2019-01-07T17:11:27,423188+00:00]
[7] [00703] [tty1] [halosghost] [tty1        ] [                    ] [0.0.0.0        ] [2019-01-07T17:11:37,209482+00:00]
```

I am running X on `tty1` (where I am also executing `physlock`) which has an entry corresponding to my username.

The journal reveals the following messages from `physlock`:

```
Jan 07 11:11:04 Phoebe physlock[1384]: pam_warn(physlock:auth): function=[pam_sm_authenticate] flags=0 service=[physlock] terminal=[<unknown>] user=[halosghost] ruser=[<unknown>] rhost=[<unknown>]
Jan 07 11:11:04 Phoebe physlock[1384]: Authentication failure
```

and I do not have `/etc/pam.d/physlock` setup, but I never have before either to my knowledge so I do not know why this would be happening.

Any thoughts? Should I open a new issue?

**Comment by muennich** [comment]
@HalosGhost: What are the exact symptons you're seeing. What version of physlock are you using and how did you build it.

**Comment by HalosGhost** [comment]
```console
$ physlock -v
physlock 11 - lock all consoles
```

I installed it from the Archlinux `[community]` repo (I did not build it myself).

When I run `physlock` (or use `C-M-l` to signal `xss-lock` to lock the session with `physlock`), I am switched to the console, console-switching is disabled, and I immediately received a flood of messages saying that authentication has failed. It does the regular revolution (3 times asking for my password, 1 time asking for the root password), but it is not waiting for my input and just immediately failing. The journal receives a slew of auth failures (that look exactly like what I posted above) as well.

**Comment by muennich** [comment]
I can not reproduce this on my up-to-date arch machine. Can you please post the contents of `/etc/pam.d/physlock` and `/etc/pam.d/other`?

**Comment by HalosGhost** [comment]
Of course:

```console
$ </etc/pam.d/physlock
zsh: no such file or directory: /etc/pam.d/physlock
$ </etc/pam.d/other
auth      required   pam_deny.so
auth      required   pam_warn.so
account   required   pam_deny.so
account   required   pam_warn.so
password  required   pam_deny.so
password  required   pam_warn.so
session   required   pam_deny.so
session   required   pam_warn.so
```

I saw in #47 your mentioning that something similar is a problem. The only reason I discounted it is that, to my knowledge, I have never modified this file, and I do not have any unhandled `pac{new,save}`s in that directory. Any idea how it could have been working before-hand without my having intervened?

**Comment by muennich** [comment]
What's the output of `pacman -Qo /etc/pam.d/other`?

**Comment by HalosGhost** [comment]
I do. Are you on IRC at all (so we can talk more directly about how to properly describe the problem and resolution recommendation)?

**Comment by muennich** [comment]
Nope. But feel free to contact me via email to do so.

**Comment by HalosGhost** [comment]
Well, I'm really sorry I wasted your time. It turns out that this issue already has a bug on the tracker: https://bugs.archlinux.org/index.php?do=details&action=details.addvote&task_id=61300

The reporter even already suggested the proper resolution (creating `/etc/pam.d/physlock` with the proper config).

Pardon the noise :/

**Comment by muennich** [comment]
No problem. Glad I could help.

**Comment by escondida** [comment]
Hey, guys. I'm happy to update the package, as recommended. muennich, would you be willing to also add the requisite pamfile to physlock, since it's not an Arch-specific problem but a probably-permanent pam change?

**Comment by escondida** [comment]
I've updated the package using the pam configuration from [here][1]. HalosGhost, does this indeed fix the problem?

[1]: https://github.com/muennich/physlock/issues/47#issuecomment-274445853

**Comment by HalosGhost** [comment]
@escondida, thanks for the quick response! I won't be able to double-check on the specific machine till tomorrow, but on another machine, I do not experience the issue with 11-4. You rock!

**Comment by muennich** [comment]
@escondida: I'm willing to ship the pam file with physlock but would prefer not to deploy it with `make install`. I do believe that the pam configuration is something that should be handled downstream, but it's maybe a bit to hard w/o any guidance like an example config file. Are you ok with this?

**Comment by escondida** [comment]
That sounds reasonable. Basically, my thought process is "if this is needed for physlock to work with future pam, it should be distributed with physlock". A line in the README explaining "please remember to install the pam module if you're using pam >= 20190105" would probably be good for anybody rolling their own.
