### ISSUE TITLE
How to Customize Locked Console Prompt?

### ISSUE THREAD

**Issue by githububub** [muennich/physlock#45]
Stable release can sed out a line in main.c but latest git has the prompt set to `Password:`. How to customize it to something like `pass:` or `hello:` or blank the prompt so that nothing shows?

**Comment by muennich** [comment]
physlock now uses pam for user authentication. The module `pam_misc` is used for password entry and prints the prompt, so that there is no easy way to customize it.

**Comment by githububub** [comment]
Thanks. It's defined in pam_get_authtok.c‎.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Bert MünnichSent: Monday, December 19, 2016 00:38To: muennich/physlockReply To: muennich/physlockCc: GitHububub; AuthorSubject: Re: [muennich/physlock] How to Customize Locked Console Prompt? (#45)physlock now uses pam for user authentication. The module pam_misc is used for password entry and prints the prompt, so that there is no easy way to customize it.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/muennich/physlock","title":"muennich/physlock","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/muennich/physlock"}},"updates":{"snippets":[{"icon":"PERSON","message":"@muennich in #45: physlock now uses pam for user authentication. The module `pam_misc` is used for password entry and prints the prompt, so that there is no easy way to customize it."}],"action":{"name":"View Issue","url":"https://github.com/muennich/physlock/issues/45#issuecomment-267909711"}}}

**Comment by Deathorn** [comment]
Please consider reopening this issue! It was very convenient to have blank or custom password prompt. As I can see it is also hardcoded in pam_get_authtok.c‎ in English - wtf, it`s 2017...if it is not possible to easily change it with pam, could you make using it optional? Thanks.
