### ISSUE TITLE
New release? Latest in AUR is 0.5

### ISSUE THREAD

**Issue by craftyguy** [muennich/physlock#46]
Hi @muennich, any chance of getting a new 'release' posted soon? [AUR still points to 0.5](https://aur.archlinux.org/packages/physlock/)(I think you're the maintainer for that PKGBUILD too?), and you have had a few interesting changes since that was released in 2015.

**Comment by muennich** [comment]
As always: I will release a new stable version as soon as all problems caused by the new changes are fixed.

**Comment by muennich** [comment]
Just released version 11.
