### ISSUE TITLE
Authentication faillure on CentOS 7.x

### ISSUE THREAD

**Issue by gitr0b** [muennich/physlock#47]
Hello, 

I am trying to lock my system with physlock: 
- physlock current git branch form 2017-01-17
- gdm
- kde
- X session :0 is on tty1
- CentOS 7 (tried some 7.2 state and again with 7.3 and all Updates from 2017-01-17)

When no one is logged in at gdm but gdm running: 
- I can log in on a text tty (tty2)
- then lock and unlock with physlock

But from xorg it does not work. 
When trying to lock from a graphical terminal, I get repeating messages on the text console: 
User: root
Authentication failed
User: root
Authentication failed
(...)

and in /var/log/messages:
Jan 17 21:17:07 hostname physlock[5756]: Authentication failure
Jan 17 21:17:07 hostname physlock[5756]: Authentication failure
(...)

and in /var/log/audit/audit.log:
type=USER_AUTH msg=audit(1484684230.555:4633): pid=5756 uid=1000 auid=1000 ses=1 msg='op=PAM:authentication grantors=? acct="root" exe="/home/user1/data/test/physlock/bin/bin/physlock" hostname=? addr=? terminal=tty2 res=failed'
type=USER_AUTH msg=audit(1484684230.557:4634): pid=5756 uid=1000 auid=1000 ses=1 msg='op=PAM:authentication grantors=? acct="root" exe="/home/user1/data/test/physlock/bin/bin/physlock" hostname=? addr=? terminal=tty2 res=failed'
(...)

I tried running with and without -d .
I tried as user and as root. 
Makes no diffenrence.. 

To make testing easier and to enable me to continue after the test without restart, I run this as root before trying to lock: 
while [[ 1 ]] ; do sleep 15s ; killall physlock ; done

Please help me to find out what happens. 
Best regards, gitr0b

**Comment by muennich** [comment]
When running from within the graphical session, it seems that physlock is not able to detect the logged in user and falls back to the owner of the corresponding tty device, which is root. So only the root user's credentials are used, as the `User: root` line before every password prompt shows.
I do not know however, why the root user's password does not work. The current HEAD version of physlock uses PAM for authentication.

**Comment by gitr0b** [comment]
It is not waiting for me to enter the root pw. 
The messages
"User: root
Authentication failed"
repeat very fast without giving me the opportunity to enter the password.

**Comment by muennich** [comment]
Can you please paste the contents of the files `/etc/pam.d/physlock` (very likely does not exist) and `/etc/pam.d/other`?

**Comment by gitr0b** [comment]
`# cat /etc/pam.d/physlock
cat: /etc/pam.d/physlock: Datei oder Verzeichnis nicht gefunden

# cat /etc/pam.d/other 
#%PAM-1.0
auth     required       pam_deny.so
account  required       pam_deny.so
password required       pam_deny.so
session  required       pam_deny.so
`

**Comment by muennich** [comment]
In order to work properly physlock needs a pam module configuration like this:
```
#%PAM-1.0
auth		required	pam_unix.so
account		required	pam_unix.so
password	required	pam_unix.so
session		required	pam_unix.so
```
You have to create `/etc/pam.d/physlock` with this content or weaken your fallback pam module config `/etc/pam.d/other` by replacing it with this.

**Comment by gitr0b** [comment]
That works. Thank you for your help! I am now able to unlock using the root password. 

But I locked as user. Shall I open another issue for that? Can physlock use the content of the $USER environment variable to determine the user name?

**Comment by muennich** [comment]
From physlock's README: _physlock tries to detect the user logged in on the active console by first searching the utmp file for an entry whose ut_line field equals the device name of the active console, e.g. "tty1". If no such entry is found, then physlock falls back to the owner of the device file of the active console. Some graphical login managers do neither write an appropriate utmp entry nor set the owner of the device file. You have to manually set up sessreg(1) in order to use physlock with such a graphical login manager._

As stated in this [comment](https://github.com/muennich/physlock/issues/44#issuecomment-268640663) on issue #44, physlock is a tool to lock the screen for the owner of the foreground console not for a remotely logged in user.

**Comment by gitr0b** [comment]
My graphical login manager gdm on centos 7 does not seem to do this. 
How can I verify?
I tried
    sessreg -a -l $DISPLAY $USER
but no change.

**Comment by muennich** [comment]
The line entry in the utmp file must match the base name of the console. So using `$DISPLAY` is wrong and something like this should do the trick:

    $ sessreg -a -l tty$(fgconsole) $USER

Setting up sessreg is also covered in the discussion of issue #31.

**Comment by gitr0b** [comment]
That works fine. Thank you.

**Comment by pavlix** [comment]
Thanks, I will try it. On the other hand why do we need to fail so badly? If the configuration is not working, I guess the program should at least write an error message and then stop fast-looping. Can we fix that?
