### ISSUE TITLE
Physlock behavior with disabled root account without password

### ISSUE THREAD

**Issue by oriansj** [muennich/physlock#51]
Debian installs default to disabling the root account when the user does not input a root password.
However in such cases physlock does the incorrect thing and allows a user who types root [ENTER] [ENTER] to bypass the security check (with a minor error message displayed).
The correct behavior is forbid root login and keep the lock in place.
Should you wish to allow an administrator to override the lock, members of the wheel group is a suitable replacement

**Comment by muennich** [comment]
What version are you running? In case it's the stable v0.5, can you please try the current master, which uses PAM for authentication?

**Comment by oriansj** [comment]
The version currently in Debian stable (Stretch) is physlock 0.4.5 and the current master does in fact correct this bug. It also don't prompt for username and a minor note you may wish to mention libpam0g-dev for builds on debian stable as sudo apt-get build-dep physlock misses it.

**Comment by muennich** [comment]
Sounds like the master is working correctly. The build dependency is something the package maintainer has to handle. I'll try to get the information to her/him.
