### ISSUE TITLE
Version number schema will stay at XY?

### ISSUE THREAD

**Issue by mika** [muennich/physlock#53]
Just to clarify as being the official Debian packager for physlock and going through the issues in Debian's BTS:

So far the versions of physlock were something like 0.4.5->0.5, now with https://github.com/muennich/physlock/commit/55c127769da5a1e0e15ec39880b308aeef7aa110 it was jumping to version "11".

Can you please acknowledge that the next versions will be increasing as 11.1 or 12 etc? (Because if the "11" wasn't meant as such and the next release will be 0.12 or so I'd have to introduce epoch versioning in the Debian packaging and we - as in Debian - try to avoid that fur a bunch of reasons :)).

Thanks!

**Comment by muennich** [comment]
I've switched to a simple integer version scheme. The current version is 11, because overall it is the 11'th release of physlock. The next version will be 12.

**Comment by mika** [comment]
Excellent, thanks for the response! Just uploaded v11 towards Debian.
