### ISSUE TITLE
fails to lock on aarch64

### ISSUE THREAD

**Issue by HalosGhost** [muennich/physlock#56]
I have a [pinebook](https://www.pine64.org/?page_id=3707) running [alarm](https://archlinuxarm.org/). After having built physlock for aarch64 and installed it, it fails to run with the following error:

```
physlock: /dev/console: VT_GETSTATE: Inappropriate ioctl for device
```

Any idea what this problem might stem from or if there is a simple way to fix it?

**Comment by muennich** [comment]
Do you have any `console=` options on your kernel command line (`grep console /proc/cmdline`)? Does it work if you change the `CONSOLE_DEVICE` variable in your `config.h` to `/dev/tty0`?

**Comment by HalosGhost** [comment]
Yes, I do actually. Here's the whole ``/proc/cmdline``:

```
console=ttyS0,115200n8 enforcing=0 cma-384M no_console_suspend androidboot.serialno=<snip> androidboot.hardware=sun50iw1p1 androidboot.selinux=permissive earlyprintk=sunxi-uart,0x01c28000 loglevel=8 root=/dev/mmcblk0p2 eth0_speed=auto
```

Though this is a weird embedded platform, I do have access to modify those arguments (though they were set by-default so I am a little wary of modifying them).

And yes! changing that option in ``config.h`` solves the issue. Is this just an oddity of the cmdline arguments on my machine?

**Comment by muennich** [comment]
You are just the first one who uses physlock on a device with a serial console. Using `/dev/tty0` is the correct device for the foreground virtual console, not `/dev/console`.

Thanks for reporting the issue and have fun.

**Comment by HalosGhost** [comment]
Cheers, thanks!
