### ISSUE TITLE
Root password is required after 3 failed attempts

### ISSUE THREAD

**Issue by kartongsaft** [muennich/physlock#59]
After three incorrect password attempts, root password is required.

![img_20171009_154846](https://user-images.githubusercontent.com/18282546/31341393-a0ccdce8-ad09-11e7-8657-1be141d16c74.jpg)

**Comment by muennich** [comment]
This is the desired--one might go so far to call it documented--behaviour.

**Comment by muennich** [comment]
It already is set to infinite. There's only one root password attempt every three user attempts.

**Comment by kartongsaft** [comment]
That's good, but why would I need to provide root's password?

**Comment by muennich** [comment]
physlock was started for a computer lab and is supposed to always let the administrator unlock the computers in case a user locked it and never came back.

**Comment by kartongsaft** [comment]
I didn't thought about that! Well the problem I see, is that after the user has not provided the right credentials after 3 attempts, the user is forced to login as root. Why not let the user decide to either login as root or try again?

**Comment by muennich** [comment]
Older version of physlock did have the behaviour you are asking for. I have changed it because others  did not like to select a user on every password prompt.
