### ISSUE TITLE
physlock causes dxvk crash on screen unlock

### ISSUE THREAD

**Issue by leewdch** [muennich/physlock#64]
I tried opening an issue on dxvk but it has been closed because apparently it's physlock that it's causing a weird window behavior when locking my screen: https://github.com/doitsujin/dxvk/issues/378

The command I use to lock my screen is `physlock -d`

Is there a particular physlock mode I can use to avoid crashes with dxvk?

**Comment by muennich** [comment]
All physlock is doing in regard to the "window system" is switching away from X/Wayland onto a virtual terminal. Do you get the same crash when switching to a vt by using the `Ctrl-Alt-[1-9]`?

**Comment by leewdch** [comment]
Yes, it happens when I switch to a vt as well. Does this mean that this is actually a dxvk error, not something that is caused by physlock, right?

**Comment by muennich** [comment]
It is definitely not a bug in physlock then.
