### ISSUE TITLE
Regression: 23227f51eab447055f21a0baa1af926c5eb3730f

### ISSUE THREAD

**Issue by esgwpl** [muennich/physlock#66]
Commit https://github.com/muennich/physlock/commit/23227f51eab447055f21a0baa1af926c5eb3730f broke physlock for me, it errors out with the following message:
`physlock: No utmp entry for tty1 found`
I compiled the previous commit to work around this issue, I'm on 64-bit Arch Linux.

**Comment by muennich** [comment]
Ouch, that commit was really bad. Sorry!
