### ISSUE TITLE
Physlock and Yubikey

### ISSUE THREAD

**Issue by dramm33** [muennich/physlock#69]
I've been using physlock without any issues for some time now using [sxhkd](https://github.com/baskerville/sxhkd) to launch physlock with a shortcut.
Recently I got a Yubikey and configured it with pam-u2f using [this as reference](https://www.jamesthebard.net/archlinux-and-u2f-login/). I can login and sudo just by pressing the button on the key.
However if I run physlock I must type my password, pressing the button on the key does no good. Maybe it is something with physlock not recognizing pam?

I created a bash script using [this as reference](https://anto.pt/usb-token-password-arch-linux/) to detect if shift is pressed and run physlock if it isn't.
This bash script in run when there is a udev event saying the the Yubikey is removed.
The script works fine and when I remove the key without pressing shift I see the physlock screen.
However after I type my password and press enter I get stuck at the physlock screen, can't change tty or do anything. Only thing left to do is press the power button to initiate shutdown.
If I type a wrong password it doesn't freeze, I just get the usual "auth wrong" message

I suspect that the script is launching physlock multiple times, could this be it?

To clarify
* physlock only unlocks with password, Yubikey doesn't work
* physlock freezes when I insert the correct password if it was launched by the script

**Comment by muennich** [comment]
What version of physlock are you running? Can you please paste the whole script?

**Comment by dramm33** [comment]
```
$ physlock -v
physlock 11 - lock all consoles
```

Sure, here it is:
```
#!/bin/bash

HOTKEY="KEY_LEFTSHIFT"

# Write message to system log
/usr/bin/logger "Screen locked because Yubikey has been disconnected."

# Check, if hotkey is not beeing pressed during lockscreen attempt
kbd_devices=`cat /proc/bus/input/devices | egrep '^H:.* kbd ' | sed 's/.*event\([0-9]\+\).*/event\1/'`
for event_dev in ${kbd_devices}; do
    evtest --query /dev/input/${event_dev} EV_KEY ${HOTKEY}
    if [[ "$?" != "0" ]]; then
        exit 0
    fi
done

# Lock the screen
physlock
```
I was thinking maybe it could be something related to who is actually running physlock? (the system and not my user?)
It still doesn't make sense though, because only the correct password makes it freeze...

PS: I also tried inserting back the Yubikey and then typing my password, but the result was the same.

**Comment by schaffer** [comment]
I managed to make physlock work with the YubiKey by using yubico-pam, which uses the challenge response feature instead of U2F.
For that I had to add `auth requisite pam_yubico.so mode=challenge-response` to /etc/pam.d/other, after `auth required pam_unix.so`.

Do you have the pam setting for u2f in /etc/pam.d/other? That might do the trick, or else you might consider switching to yubico-pam.

**Comment by dramm33** [comment]
Yeah, adding `auth sufficient pam_u2f.so authfile=/etc/u2f_mappings` did the trick. Thanks!
I didn't realize that physlock just read /etch/pam.d/other and not any of the other files that included /etc/pam.d/system-auth

However physlock still hangs when I use my script..
@schaffer could you please try the script to see if you physlock also hangs with you?

Just create /etc/udev/rules.d/71-autolockscreen.rules and add the following line: `SUBSYSTEM=="input", ACTION=="remove", ENV{ID_VENDOR}=="Yubico", RUN+="path/to/script"`
Don't forget to change the path to wherever you put the script, then do:
```
$ udevadm control --reload
$ udevadm trigger
```


Off-topic: I'm using U2F so I don't have to dedicate a slot in the Yubikey just for my authenticating my computer.

**Comment by muennich** [comment]
Physlock does not read any PAM config files on its own; libpam does that. If you haven't configured PAM for physlock by creating a suitable `/etc/pam.d/physlock` file then the lib automatically falls back to `/etc/pam.d/other`. 

Regarding the script: Does the hang up only happen when the script is launched via the udev rule or does it also occur when you manually call the script?

**Comment by dramm33** [comment]
Only happens when launched via the udev rule.

I created `/etc/pam.d/physlock` and removed the added lone form `/etc/pam.d/other`. Manually calling physlock (directly or via script) still works as expected.
I'm only getting the freeze with the udev rule.

Also, if I remove the key (udev triggers script and physlock is launched) it asks me for password as expected. If a plug the key back in and just press enter (or type wrong password) I don't get asked for the password again, instead physlock wait for the button on the key to be pressed (which is the desired behavior).
However when I press the button physlock hangs just as if I had typed the correct password.

**Comment by schaffer** [comment]
I tried the script and it gets triggered multiple times.
Looks like the yubikey is actually multiple devices, then the script gets called multiple times every time you remove it.

I had the same problem in the past and fixed it by using xss-lock and loginctl.

My setup is the following:
/etc/udev/rules.d/yubikey.rules:
```ACTION=="remove", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0407", RUN+="/path/to/lockscript"```

lockscript:
```
loginctl --no-legend list-sessions | grep -E '\bseat[0-9]+\b' | awk '{ print $1 }' | xargs -n1 loginctl lock-session
```

At the start of my session I run:
`xss-lock --quiet physlock &> /dev/null &`

loginctl can handle it being called multiple times, and xss-lock is there to listen to loginctl and run physlock.

**Comment by dramm33** [comment]
Just tried using your version of the lockscript using xss-lock and loginctl. Works great!

The only thing I didn't understand is why you are redirecting stdout and stderr to null (aka getting rid of them).

@muennich feel free to close the issue if you think physlock should not handle multiple calls.

**Comment by schaffer** [comment]
> The only thing I didn't understand is why you are redirecting stdout and stderr to null (aka getting rid of them).

No special reason, I'll edit the post to remove that.
