### ISSUE TITLE
Infinite loop on Arch Linux

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [muennich/physlock#72]
I'm reporting upstream a bug described in https://bugs.archlinux.org/task/61300.

I'm aware of #47 and required modification to PAM configuration, however, I believe, that this behaviour is a bug, as it results in situation, when only thing you can do is to reboot your machine or kill the process over SSH.

Here is also the screenshot of what's happening (probably known issue) from virtual box:
![selection_065](https://user-images.githubusercontent.com/16538006/50818800-7390cd80-1328-11e9-8cd4-5be7ea16dafe.png)

Steps to reproduce (assuming Vagrant with VirtualBox is installed):
- Execute following commands locally:
  ```
  echo "Vagrant.configure("2") do |config|
    config.vm.box = "archlinux/archlinux"
    config.vm.provider "virtualbox" do |v|
      v.gui = true
    end
  end" > Vagrantfile
  vagrant up
  vagrant ssh
  ```
- In SSH session, execute following:
  ```
  echo "[options]
  HoldPkg     = pacman glibc
  Architecture = auto
  CheckSpace
  SigLevel    = Required DatabaseOptional
  LocalFileSigLevel = Optional
  [testing]
  Include = /etc/pacman.d/mirrorlist
  [core]
  Include = /etc/pacman.d/mirrorlist
  [extra]
  Include = /etc/pacman.d/mirrorlist
  [community]
  Include = /etc/pacman.d/mirrorlist" | sudo tee /etc/pacman.conf
  sudo pacman -Sy pambase physlock
  sudo rm /etc/pam.d/physlock
  physlock -m
  ```
- In the GUI, you should be able to see infinite loop and physlock does not respond to Ctrl+C.

**Comment by muennich** [comment]
What do you want me to do?

**Comment by mateusz-gozdek-sociomantic** [comment]
I'd expect physlock to gracefully handle PAM misconfiguration, for example, by checking the configuration before entering the loop.

**Comment by muennich** [comment]
I expect the packager/user who installs physlock to do the PAM configuration. An approriate PAM configuration is a necessity for any application that uses PAM. But an application cannot force the configuration upon the user because it does not know what authentication mechanisms the user wants to use--think of yubi keys.

**Comment by muennich** [comment]
I am working on making it more clearer as stated in the issue you've referenced.

**Comment by mateusz-gozdek-sociomantic** [comment]
Shouldn't there be an issue about it on GitHub then?

**Comment by muennich** [comment]
You've already referenced it: #47.

**Comment by mateusz-gozdek-sociomantic** [comment]
But it's closed, meaning it is resolved, when in reality, you are still working on it, as you told, so it is not resolved. Maybe it should be reopened then.
