### ISSUE TITLE
Provide example PAM config

### ISSUE THREAD

**Issue by muennich** [muennich/physlock#73]
Make it as generic as possible so that it can be deployed by users of all distros without modification. Will it support yubi keys and other forms of authentication? Deploy it in `make install`?
Addresses questions regarding PAM configuration in issues #44, #47, #60, #69, #72.

**Comment by escondida** [comment]
Perhaps there could be an optional "make install-pam" target or something to that effect. Not strictly necessary, but since the question's on the table. The alternate would just be documenting that newer pams need the file installed.

Thanks (-:

**Comment by muennich** [comment]
In the end I decided against any form of deployment, because all of the PAM config files on my machine are provided by the distribution and the upstream projects only have sample config files.

**Comment by escondida** [comment]
Fair enough!
