### ISSUE TITLE
"No utmp entry for tty... found" issue with v12

### ISSUE THREAD

**Issue by mika** [muennich/physlock#74]
Thanks for providing v12 so timely!
I just worked on the packaging for Debian, but I ran into a similar situation as the one we had in #44:

```
root@grml ~ # physlock
physlock: No utmp entry for tty1 found
1 root@grml ~ # fgconsole 
1
root@grml ~ # tty
/dev/tty1
root@grml ~ # ls -la /dev/tty1
crw--w---- 1 root tty 4, 1 Jan 27 22:01 /dev/tty1
```

Also when providing a PAM configuration file like:

```
root@grml ~ # cat /etc/pam.d/physlock
#%PAM-1.0
auth required pam_unix.so
account required pam_unix.so
password required pam_unix.so
session required pam_unix.so
```

..  or the one provided as `physlock.pam` it sadly still fails.

When I manually execute:

```
# sessreg -a -l tty$(fgconsole) $USER
```

then it works again.

It also works fine for the users who have a proper utmp entry, but shouldn't the fallback that used to work with physlock <=v11 (to use owner of tty device if there's no utmp entry) continue to work with v12 as well? (I'm aware of the `The used mechanism is selected at build time by setting the `SESSION` macro. The default is `utmp`.` note from the README, but a runtime fallback option would be good to have.)

Thanks!

**Comment by muennich** [comment]
I did not think of issue 44 when making the user detection mechanism only selectable at compile time. physlock now supports and tries them all. Can you please try the current master? Seems like the next release is just around the corner...

**Comment by mika** [comment]
Yes, ec5198aa20fb4c7bada09381f97b8097255498f6 indeed fixes the issue and seems to work just as needed! If you manage to provide this as new release I'd go forward with the upload towards Debian! Thanks for fast response and the fix!

**Comment by muennich** [comment]
I've just pushed v13. Thanks for your work at the Debian end.
