### ISSUE TITLE
Program hangs after "physlock -l" then "physlock"

### ISSUE THREAD

**Issue by alanxoc3** [muennich/physlock#81]
After executing physlock as root on a tty, physlock freezes my computer, leaving me with only a hard reboot:
```
physlock -l
physlock
```
It doesn't allow me to type my password and doesn't give me a prompt after executing physlock. But this sequence does work as intended:
```
physlock -l
physlock -L
physlock
```

**Comment by xyb3rt** [comment]
Thanks for reporting the issue.
