### ISSUE TITLE
Command line option for password feedback?

### ISSUE THREAD

**Issue by Amanita-muscaria** [muennich/physlock#90]
This is a feature request, not an actual issue. Is it possible to implement password feedback? I like having something to show me how far into my password I've gotten.

**Comment by xyb3rt** [comment]
The password prompt is not part of physlock but of PAM's `misc_conv` conversation module. I do not want to write a new conversation module for this. Sorry.

**Comment by Amanita-muscaria** [comment]
Oh, sorry. I didn't realize that. Sorry for the noise.
