### ISSUE TITLE
Allow message to be multiline

### ISSUE THREAD

**Issue by f0s3** [muennich/physlock#92]
I want my login screen to have this:
```
Hello
world
Password:
```
And I could not achieve this for two reasons:
 - Trying `-p "Hello\nworld"` doesn't add newline char
 - There is an empty newline between `world` and `Password:` which I couldn't remove

**Comment by xyb3rt** [comment]
```
-p "Hello
world"
```
should fix point one. The newline addressed in point two is intentional, because the message is not part of the password prompt.
